device: null
seed: 10

model: 
  sim_n_gaussians: 8
  reco_n_gaussians: 8

geometry:
  sources:
    - [-1.0, -1.0]
  receivers:
    n_receivers: 128
    x_coordinate: 4.0
    y_min: -3.0
    y_max: 1.0

physics:
  initial_positions:
    - [1.0, 1.0]
  initial_accelerations:
    - [0.0, -9.81]
  omega_range: [2.0, 6.0]
  n_projections: 150
  duration: 1.5
  # initial_velocities: [0.75, 0.5]
  initial_velocities: [0.1, 0.25]

reconstruction:
  n_trajectory_trials: 20
  n_omega_inits: 5
  max_iterations: 500
  tolerance: 1e-5

output:
  directory: "data/"
  save_plots: true
  save_animations: true
  verbose: true

analysis:
  enabled: true
  skip_errors: false
  skip_plots: false
  skip_animations: false
